### PR TITLE
Update vm install script

### PR DESCRIPTION
**Pull request by albal**
Changes to use latest version of Kubernetes and update Java version to work with current version of Jenkins:

- Add `set -e` to exit script on first error
- Use Kubernetes version 1.26.3
- Use containerd instead of Docker
- Pin Kubernetes version in apt (`apt-mark`)
- Point to current weave repo
- Make system changes necessary for later versions of Kubernetes
- using later version of java `openjdk-11-jdk`
- provide output of Jenkins passcode at end of script

This scripts has been tested on Ubuntu 18.04.06 LTS and Ubuntu 22.04.01 LTS

Previously the script was broken as the Weave URL is no longer reachable and Jenkins no longer supports openjdk-8-jdk

### CODE REVIEW

**Comment by fireflycons** [comment]
```
.........----------------#################._.-.-JENKINS-.-._.#################----------------.........
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Hit:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:1 https://pkg.jenkins.io/debian-stable binary/ InRelease
Get:6 https://pkg.jenkins.io/debian-stable binary/ Release [2044 B]
Get:7 https://pkg.jenkins.io/debian-stable binary/ Release.gpg [833 B]
Hit:8 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Ign:7 https://pkg.jenkins.io/debian-stable binary/ Release.gpg
Reading package lists... Done
W: GPG error: https://pkg.jenkins.io/debian-stable binary/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BA31D57EF5975CA
E: The repository 'http://pkg.jenkins.io/debian-stable binary/ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://apt.kubernetes.io/dists/kubernetes-xenial/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
ubuntu@ip-172-31-9-140:~/src/devsecops/setup/vm-install-script$ systemctl status jenkins
```

**Comment by fireflycons** [comment]
Looks like you did the changes in Windows.

Can you convert CRLF -> LF and also set execute perms on the script:

```
git update-index --chmod=+x install-script.sh
```

**Comment by albal** [comment]
> Can you convert CRLF -> LF and also set execute perms on the script:

The file is already in LF only format.  dos2unix install-script.sh made no changes

> ```
> git update-index --chmod=+x install-script.sh
> ```

I've pushed this update

**Comment by albal** [comment]
> ```
> W: http://apt.kubernetes.io/dists/kubernetes-xenial/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
> ubuntu@ip-172-31-9-140:~/src/devsecops/setup/vm-install-script$ systemctl status jenkins
> ```
This still works on Ubuntu 22.04 LTS but is left in to be compatible with Ubuntu 18 and 20.

**Pull request merged**
